{{- if .Values.autoscaling.enabled -}}
{{- $appName := include "gdc.name" . -}}
---
{{- if .Capabilities.APIVersions.Has "autoscaling/v2" }}
apiVersion: autoscaling/v2
{{- else }}
apiVersion: autoscaling/v2beta2
{{- end }}
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $appName }}-hpa
  namespace: {{ template "common.namespace" . }}
  labels:
    {{- include "gdc.labels" . | nindent 4 }}                            
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $appName }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  {{- with .Values.autoscaling.behavior }}
  behavior:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  metrics: {{ toYaml .Values.autoscaling.metrics | nindent 2 }}
{{- end }} 
